INCLUDE_PATH    := ./ ../external/include/ ../common/
SOURCE_PATH     := ./ ../common/
DEPENDENCY_PATH := dep
OBJECT_PATH     := obj

EXTERNAL_LIBS := $(wildcard ../external/lib/*.a)
LDLIBS := -lm -lpthread -lglut -lopengl32 -lglu32


CFLAGS += -O3

include ../makefile.mk
